### PR TITLE
Replace canoe picture with better default image

### LINKED ISSUE #108: Add "your club image here" watermark on canoe placeholder image
__Description:__
Make a starter page which helps users build their first website.

__Requires:__
* Sign up
* Image Uploader (#77)

__Breakdown:__
- [x] Make watermarked image
- [x] Upload into rep

__Time Estimation:__
0.5 hrs.

### PR DESCRIPTION
**Pull request by kelseyll**
Decided not to use "add your club image here"  wording on the default image for two reasons:
- When the browser is resized, the words within the photo would compress and look bad
- It competed too much with the instructions in the description, and the instructions in the toast (too many instructions at once looked overwhelming and cluttered)

image

Fixes #108

### CODE REVIEW

**Comment by hwkr** [comment]
Is the watermark dynamic? Or just to show that it's sample image?

**Comment by kelseyll** [comment]
Just to show it's a sample image

**Comment by hwkr** [comment]
Okay, sounds good

**Comment by kelseyll** [comment]
on second thought I'm just going to remove the watermark all together and just leave the new image there

lolol

**Pull request merged**
