### PR TITLE
Fixed Logic in Team Editor Section

### LINKED ISSUE #93: Fix Unique 'Key' Prop Error in Team component(s)
__Description:__
Basically [this](http://stackoverflow.com/questions/28329382/understanding-unique-keys-for-array-children-in-react-js). 

__Requires:__
* unique 'key' prop

__Breakdown:__

__Time Estimation:__
0.25 hrs.

### LINKED ISSUE #95: Fix Logic in Team Editor Section for Updating the Data Object
__Description:__
Faulty logic in Team Editor Section causes a "Converting circular structure to JSON" error.

__Requires:__
* debug & refactor

__Breakdown:__
- [x] try editing a team member's info and observe error
- [x] fix logic

__Time Estimation:__
1 hrs.

### PR DESCRIPTION
**Pull request by okjuan**
resolves #95 resolves #93

### CODE REVIEW

**Comment by hwkr** [comment]
Does this code work?

**Comment by okjuan** [comment]
@hwkr Yes, it is tested. I looked at the React elements and console as I made changes and checked that the new data was saved by going to the corresponding /site page.

**Comment by okjuan** [comment]
...except that new changes were pushed to develop since my testing. Status TBD.

**Comment by hwkr** [comment]
Okay, what does the data look like for team people right now?

**Comment by okjuan** [comment]
Not terribly proud of the structure -- could have just been a list. The keys in the `team` object are arbitrary: they are just iterated over.

```
site: {
  sections: {
    ...
    team: {
      person1: {
        name: "Michael Scarn"
        position: "Regional Manager"
        email: "thatswhatshesaid@uvic.ca"
      }
      person2: {
        ...
      }
      ...
    }
  }
}
```

**Comment by hwkr** [comment]
Okay, let's make it a list the while we're still working on it?

**Pull request merged**
